pub const CLEANUP_BLOCK_ERROR: i32 = -32001;
pub const MISSING_SLOT_ERROR: i32 = -32007;
pub const MISSING_OR_SKIPPED_SLOT_ERROR: i32 = -32009;
pub const NOT_AVAILABLE_SLOT_ERROR: i32 = -32004;

pub const MISSING_BLOCKS_ERRORS: [i32; 4] = [MISSING_SLOT_ERROR, MISSING_OR_SKIPPED_SLOT_ERROR, NOT_AVAILABLE_SLOT_ERROR, CLEANUP_BLOCK_ERROR];
