[package]
name = "localizer"
version = "1.0.0"
edition = { workspace = true }

[dependencies]
i18n-embed = { workspace = true }
i18n-embed-fl = { workspace = true }
once_cell = { workspace = true }
rust-embed = { workspace = true }
