// Copyright (c). Gem Wallet. All rights reserved.

import SwiftUI

public extension Images {
    struct System {
        public static let settings = Image(systemName: SystemImage.settings)
        public static let qrCodeViewfinder = Image(systemName: SystemImage.qrCodeViewfinder)
        public static let qrCode = Image(systemName: SystemImage.qrCode)
        public static let paste = Image(systemName: SystemImage.paste)
        public static let copy = Image(systemName: SystemImage.copy)
        public static let arrowSwap = Image(systemName: SystemImage.arrowSwap)
        public static let paperplane = Image(systemName: SystemImage.paperplane)
        public static let chevronDown = Image(systemName: SystemImage.chevronDown)
        public static let chevronRight = Image(systemName: SystemImage.chevronRight)
        public static let clear = Image(systemName: SystemImage.clear)
        public static let hide = Image(systemName: SystemImage.hide)
        public static let faceid = Image(systemName: SystemImage.faceid)
        public static let network = Image(systemName: SystemImage.network)
        public static let globe = Image(systemName: SystemImage.globe)
        public static let share = Image(systemName: SystemImage.share)
        public static let lock = Image(systemName: SystemImage.lock)
        public static let delete = Image(systemName: SystemImage.delete)
        public static let checkmark = Image(systemName: SystemImage.checkmark)
        public static let ellipsis = Image(systemName: SystemImage.ellipsis)
        public static let info = Image(systemName: SystemImage.info)
        public static let eyeglasses = Image(systemName: SystemImage.eyeglasses)
        public static let plus = Image(systemName: SystemImage.plus)
        public static let eye = Image(systemName: SystemImage.eye)
        public static let search = Image(systemName: SystemImage.search)
        public static let exclamationmarkTriangleFill = Image(systemName: SystemImage.exclamationmarkTriangleFill)
        public static let exclamationmarkTriangle = Image(systemName: SystemImage.exclamationmarkTriangle)
        public static let gallery = Image(systemName: SystemImage.gallery)
        public static let photo = Image(systemName: SystemImage.photo)
        public static let xmarkCircle = Image(systemName: SystemImage.xmarkCircle)
        public static let xmark = Image(systemName: SystemImage.xmark)
        public static let bell = Image(systemName: SystemImage.bell)
        public static let bellFill = Image(systemName: SystemImage.bellFill)
        public static let pin = Image(systemName: SystemImage.pin)
        public static let unpin = Image(systemName: SystemImage.unpin)
        public static let filter = Image(systemName: SystemImage.filter)
        public static let filterFill = Image(systemName: SystemImage.filterFill)
        public static let book = Image(systemName: SystemImage.book)
        public static let starFill = Image(systemName: SystemImage.starFill)
        public static let textPageFill = Image(systemName: SystemImage.textPageFill)
        public static let checkmarkCircle = Image(systemName: SystemImage.checkmarkCircle)
        public static let circle = Image(systemName: SystemImage.circle)
        public static let dollar = Image(systemName: SystemImage.dollarsign)
        public static let wallet = Image(systemName: SystemImage.wallet)
        public static let bitcoin = Image(systemName: SystemImage.bitcoin)
        public static let arrowTriangleUp = Image(systemName: SystemImage.arrowTriangleUp)
        public static let arrowTriangleDown = Image(systemName: SystemImage.arrowTriangleDown)
        public static let person = Image(systemName: SystemImage.person)
        public static let personBadgePlus = Image(systemName: SystemImage.personBadgePlus)
        public static let checkmarkSealFill = Image(systemName: SystemImage.checkmarkSealFill)
    }
}
