use crate::block_explorer::BlockExplorer;
use crate::chain_evm::EVMChain;
use crate::explorers::metadata::{Explorer, Metadata, ADDRESS_PATH, TOKEN_PATH, TX_PATH};

pub struct EtherScan;

impl EtherScan {
    pub fn boxed(chain: EVMChain) -> Box<dyn BlockExplorer> {
        match chain {
            EVMChain::Ethereum => Explorer::boxed(Metadata {
                name: "Etherscan",
                base_url: "https://etherscan.io",
                tx_path: TX_PATH,
                address_path: ADDRESS_PATH,
                token_path: Some(TOKEN_PATH),
                validator_path: None,
            }),
            EVMChain::SmartChain => Explorer::boxed(Metadata {
                name: "BscScan",
                base_url: "https://bscscan.com",
                tx_path: TX_PATH,
                address_path: ADDRESS_PATH,
                token_path: Some(TOKEN_PATH),
                validator_path: None,
            }),
            EVMChain::Polygon => Explorer::boxed(Metadata {
                name: "PolygonScan",
                base_url: "https://polygonscan.com",
                tx_path: TX_PATH,
                address_path: ADDRESS_PATH,
                token_path: Some(TOKEN_PATH),
                validator_path: None,
            }),
            EVMChain::Arbitrum => Explorer::boxed(Metadata {
                name: "ArbiScan",
                base_url: "https://arbiscan.io",
                tx_path: TX_PATH,
                address_path: ADDRESS_PATH,
                token_path: Some(TOKEN_PATH),
                validator_path: None,
            }),
            EVMChain::Optimism => Explorer::boxed(Metadata {
                name: "Etherscan",
                base_url: "https://optimistic.etherscan.io",
                tx_path: TX_PATH,
                address_path: ADDRESS_PATH,
                token_path: Some(TOKEN_PATH),
                validator_path: None,
            }),
            EVMChain::Base => Explorer::boxed(Metadata {
                name: "BaseScan",
                base_url: "https://basescan.org",
                tx_path: TX_PATH,
                address_path: ADDRESS_PATH,
                token_path: Some(TOKEN_PATH),
                validator_path: None,
            }),
            EVMChain::AvalancheC => Explorer::boxed(Metadata {
                name: "SnowScan",
                base_url: "https://snowscan.xyz",
                tx_path: TX_PATH,
                address_path: ADDRESS_PATH,
                token_path: Some(TOKEN_PATH),
                validator_path: None,
            }),
            EVMChain::OpBNB => Explorer::boxed(Metadata {
                name: "opBNBScan",
                base_url: "https://opbnb.bscscan.com",
                tx_path: TX_PATH,
                address_path: ADDRESS_PATH,
                token_path: Some(TOKEN_PATH),
                validator_path: None,
            }),
            EVMChain::Fantom => Explorer::boxed(Metadata {
                name: "FTMScan",
                base_url: "https://ftmscan.com",
                tx_path: TX_PATH,
                address_path: ADDRESS_PATH,
                token_path: Some(TOKEN_PATH),
                validator_path: None,
            }),
            EVMChain::Gnosis => Explorer::boxed(Metadata {
                name: "GnosisScan",
                base_url: "https://gnosisscan.io",
                tx_path: TX_PATH,
                address_path: ADDRESS_PATH,
                token_path: Some(TOKEN_PATH),
                validator_path: None,
            }),
            EVMChain::Manta => Explorer::boxed(Metadata {
                name: "Socialscan",
                base_url: "https://manta.socialscan.io",
                tx_path: TX_PATH,
                address_path: ADDRESS_PATH,
                token_path: Some(TOKEN_PATH),
                validator_path: None,
            }),
            EVMChain::Blast => Explorer::boxed(Metadata {
                name: "BlastScan",
                base_url: "https://blastscan.io",
                tx_path: TX_PATH,
                address_path: ADDRESS_PATH,
                token_path: Some(TOKEN_PATH),
                validator_path: None,
            }),
            EVMChain::Linea => Explorer::boxed(Metadata {
                name: "LineaScan",
                base_url: "https://lineascan.build",
                tx_path: TX_PATH,
                address_path: ADDRESS_PATH,
                token_path: Some(TOKEN_PATH),
                validator_path: None,
            }),
            EVMChain::ZkSync => Explorer::boxed(Metadata {
                name: "zkSync Era Explorer",
                base_url: "https://era.zksync.network",
                tx_path: TX_PATH,
                address_path: ADDRESS_PATH,
                token_path: Some(TOKEN_PATH),
                validator_path: None,
            }),
            EVMChain::Celo => Explorer::boxed(Metadata {
                name: "CeloScan",
                base_url: "https://celoscan.io",
                tx_path: TX_PATH,
                address_path: ADDRESS_PATH,
                token_path: Some(TOKEN_PATH),
                validator_path: None,
            }),
            EVMChain::Mantle => Explorer::boxed(Metadata {
                name: "MantleScan",
                base_url: "https://mantlescan.xyz",
                tx_path: TX_PATH,
                address_path: ADDRESS_PATH,
                token_path: Some(TOKEN_PATH),
                validator_path: None,
            }),
            EVMChain::World => Explorer::boxed(Metadata {
                name: "WorldScan",
                base_url: "https://worldscan.org",
                tx_path: TX_PATH,
                address_path: ADDRESS_PATH,
                token_path: Some(TOKEN_PATH),
                validator_path: None,
            }),
            EVMChain::Sonic => Explorer::boxed(Metadata {
                name: "SonicScan",
                base_url: "https://sonicscan.org",
                tx_path: TX_PATH,
                address_path: ADDRESS_PATH,
                token_path: Some(TOKEN_PATH),
                validator_path: None,
            }),
            EVMChain::Abstract => Explorer::boxed(Metadata {
                name: "Abscan",
                base_url: "https://abscan.org",
                tx_path: TX_PATH,
                address_path: ADDRESS_PATH,
                token_path: Some(TOKEN_PATH),
                validator_path: None,
            }),
            EVMChain::Berachain => Explorer::boxed(Metadata {
                name: "Berascan",
                base_url: "https://berascan.com",
                tx_path: TX_PATH,
                address_path: ADDRESS_PATH,
                token_path: Some(TOKEN_PATH),
                validator_path: None,
            }),
            EVMChain::Unichain => Explorer::boxed(Metadata {
                name: "Uniscan",
                base_url: "https://uniscan.xyz",
                tx_path: TX_PATH,
                address_path: ADDRESS_PATH,
                token_path: Some(TOKEN_PATH),
                validator_path: None,
            }),
            EVMChain::Monad => Explorer::boxed(Metadata {
                name: "Monad",
                base_url: "https://testnet.monadexplorer.com",
                tx_path: TX_PATH,
                address_path: ADDRESS_PATH,
                token_path: Some(TOKEN_PATH),
                validator_path: None,
            }),
            EVMChain::Hyperliquid => Explorer::boxed(Metadata {
                name: "HyperEvmScan",
                base_url: "https://hyperevmscan.io",
                tx_path: TX_PATH,
                address_path: ADDRESS_PATH,
                token_path: Some(TOKEN_PATH),
                validator_path: None,
            }),
            _ => todo!(),
        }
    }
}
