DROP TABLE IF EXISTS assets_usage_ranks CASCADE;
DROP TABLE IF EXISTS assets_addresses CASCADE;
DROP TABLE IF EXISTS assets_links CASCADE;
DROP TABLE IF EXISTS assets_tags CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS assets CASCADE;
DROP TYPE IF EXISTS link_type CASCADE;
DROP TYPE IF EXISTS asset_type CASCADE;
