[profile.dev]
# Disabling debug info speeds up builds a bunch, inspired by rust-analyzer.
debug = 0

[profile.release]
# https://github.com/johnthagen/min-sized-rust
strip = true
codegen-units = 1
lto = true
opt-level = "z"
