[package]
name = "security_hashdit"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
reqwest-enum = { workspace = true }
reqwest = { workspace = true }

security_provider = { path = "../security_provider" }
