use crate::asset_constants::{
    WETH_ARB_CONTRACT, WETH_BASE_CONTRACT, WETH_BLAST_CONTRACT, WETH_ETH_CONTRACT, WETH_INK_CONTRACT, WETH_LINEA_CONTRACT, WETH_OP_CONTRACT, WETH_OPSTACK_CONTRACT,
    WETH_UNICHAIN_CONTRACT, WETH_WORLD_CONTRACT, WETH_ZKSYNC_CONTRACT,
};
use crate::{AssetType, Chain, ChainType};

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum ChainStack {
    Native,
    Optimism,
    ZkSync,
}

#[derive(Debug, Clone)]
pub struct EvmChainConfig {
    pub min_priority_fee: u64,
    pub chain_stack: ChainStack,
    pub is_ethereum_layer2: bool,
    pub weth_contract: Option<&'static str>,
}

#[derive(Debug, Clone)]
pub struct StakeChainConfig {
    pub lock_time: u64,
    pub min_stake_amount: u64,
    pub change_amount_on_unstake: bool,
    pub can_redelegate: bool,
    pub can_withdraw: bool,
    pub can_claim_rewards: bool,
    pub reserved_for_fees: u64,
}

#[derive(Debug, Clone)]
pub struct ChainConfig {
    pub chain: Chain,
    pub network_id: &'static str,
    pub denom: Option<&'static str>,
    pub slip44: i64,
    pub chain_type: ChainType,
    pub default_asset_type: Option<AssetType>,
    pub account_activation_fee: Option<i32>,
    pub token_activation_fee: Option<i32>,
    pub minimum_account_balance: Option<u64>,
    pub block_time: u32,
    pub rank: i32,
    pub is_swap_supported: bool,
    pub is_nft_supported: bool,
    pub is_utxo: bool,
    pub evm: Option<EvmChainConfig>,
    pub stake: Option<StakeChainConfig>,
}

// Centralized chain configurations. Add new chains here.
static CHAIN_CONFIGS: &[ChainConfig] = &[
    ChainConfig {
        chain: Chain::Bitcoin,
        network_id: "000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f",
        denom: None,
        slip44: 0,
        chain_type: ChainType::Bitcoin,
        default_asset_type: None,
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 600_000,
        rank: 100,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: true,
        evm: None,
        stake: None,
    },
    ChainConfig {
        chain: Chain::BitcoinCash,
        network_id: "000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f",
        denom: None,
        slip44: 145,
        chain_type: ChainType::Bitcoin,
        default_asset_type: None,
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 600_000,
        rank: 40,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: true,
        evm: None,
        stake: None,
    },
    ChainConfig {
        chain: Chain::Litecoin,
        network_id: "12a765e31ffd4059bada1e25190f6e98c99d9714d334efa41a195a7e7e04bfe2",
        denom: None,
        slip44: 2,
        chain_type: ChainType::Bitcoin,
        default_asset_type: None,
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 120_000,
        rank: 30,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: true,
        evm: None,
        stake: None,
    },
    ChainConfig {
        chain: Chain::Ethereum,
        network_id: "1",
        denom: None,
        slip44: 60,
        chain_type: ChainType::Ethereum,
        default_asset_type: Some(AssetType::ERC20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 12_000,
        rank: 85,
        is_swap_supported: true,
        is_nft_supported: true,
        is_utxo: false,
        evm: Some(EvmChainConfig {
            min_priority_fee: 100_000_000,
            chain_stack: ChainStack::Native,
            is_ethereum_layer2: false,
            weth_contract: Some(WETH_ETH_CONTRACT),
        }),
        stake: Some(StakeChainConfig {
            lock_time: 259200,
            min_stake_amount: 100_000_000_000_000_000,
            change_amount_on_unstake: true,
            can_redelegate: false,
            can_withdraw: true,
            can_claim_rewards: false,
            reserved_for_fees: 5_000_000_000_000_000,
        }),
    },
    ChainConfig {
        chain: Chain::SmartChain,
        network_id: "56",
        denom: None,
        slip44: 9006,
        chain_type: ChainType::Ethereum,
        default_asset_type: Some(AssetType::BEP20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 1_000,
        rank: 80,
        is_swap_supported: true,
        is_nft_supported: true,
        is_utxo: false,
        evm: Some(EvmChainConfig {
            min_priority_fee: 50_000_000,
            chain_stack: ChainStack::Native,
            is_ethereum_layer2: false,
            weth_contract: Some("0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c"),
        }),
        stake: Some(StakeChainConfig {
            lock_time: 604_800,
            min_stake_amount: 1_000_000_000_000_000_000,
            change_amount_on_unstake: true,
            can_redelegate: true,
            can_withdraw: true,
            can_claim_rewards: false,
            reserved_for_fees: 250_000_000_000_000,
        }),
    },
    ChainConfig {
        chain: Chain::Solana,
        network_id: "5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d",
        denom: None,
        slip44: 501,
        chain_type: ChainType::Solana,
        default_asset_type: Some(AssetType::SPL),
        account_activation_fee: None,
        token_activation_fee: Some(2_039_280),
        minimum_account_balance: Some(890_880),
        block_time: 500,
        rank: 80,
        is_swap_supported: true,
        is_nft_supported: true,
        is_utxo: false,
        evm: None,
        stake: Some(StakeChainConfig {
            lock_time: 259_200,
            min_stake_amount: 10_000_000,
            change_amount_on_unstake: false,
            can_redelegate: false,
            can_withdraw: true,
            can_claim_rewards: false,
            reserved_for_fees: 5_000_000,
        }),
    },
    ChainConfig {
        chain: Chain::Polygon,
        network_id: "137",
        denom: None,
        slip44: 60,
        chain_type: ChainType::Ethereum,
        default_asset_type: Some(AssetType::ERC20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 3_000,
        rank: 30,
        is_swap_supported: true,
        is_nft_supported: true,
        is_utxo: false,
        evm: Some(EvmChainConfig {
            min_priority_fee: 30_000_000_000,
            chain_stack: ChainStack::Native,
            is_ethereum_layer2: false,
            weth_contract: Some("0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270"),
        }),
        stake: None,
    },
    ChainConfig {
        chain: Chain::Thorchain,
        network_id: "thorchain-1",
        denom: Some("rune"),
        slip44: 931,
        chain_type: ChainType::Cosmos,
        default_asset_type: None,
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 2_000,
        rank: 30,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: None,
        stake: None,
    },
    ChainConfig {
        chain: Chain::Cosmos,
        network_id: "cosmoshub-4",
        denom: Some("uatom"),
        slip44: 118,
        chain_type: ChainType::Cosmos,
        default_asset_type: None,
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 6_000,
        rank: 40,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: None,
        stake: Some(StakeChainConfig {
            lock_time: 1_814_400,
            min_stake_amount: 0,
            change_amount_on_unstake: true,
            can_redelegate: true,
            can_withdraw: false,
            can_claim_rewards: true,
            reserved_for_fees: 25_000,
        }),
    },
    ChainConfig {
        chain: Chain::Osmosis,
        network_id: "osmosis-1",
        denom: Some("uosmo"),
        slip44: 118,
        chain_type: ChainType::Cosmos,
        default_asset_type: None,
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 6_000,
        rank: 50,
        is_swap_supported: false,
        is_nft_supported: false,
        is_utxo: false,
        evm: None,
        stake: Some(StakeChainConfig {
            lock_time: 1_209_600,
            min_stake_amount: 0,
            change_amount_on_unstake: true,
            can_redelegate: true,
            can_withdraw: false,
            can_claim_rewards: true,
            reserved_for_fees: 10_000,
        }),
    },
    ChainConfig {
        chain: Chain::Arbitrum,
        network_id: "42161",
        denom: None,
        slip44: 60,
        chain_type: ChainType::Ethereum,
        default_asset_type: Some(AssetType::ERC20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 1_000,
        rank: 30,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: Some(EvmChainConfig {
            min_priority_fee: 10_000_000,
            chain_stack: ChainStack::Native,
            is_ethereum_layer2: true,
            weth_contract: Some(WETH_ARB_CONTRACT),
        }),
        stake: None,
    },
    ChainConfig {
        chain: Chain::Ton,
        network_id: "F6OpKZKqvqeFp6CQmFomXNMfMj2EnaUSOXN+Mh+wVWk=",
        denom: None,
        slip44: 607,
        chain_type: ChainType::Ton,
        default_asset_type: Some(AssetType::JETTON),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 5_000,
        rank: 50,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: None,
        stake: None,
    },
    ChainConfig {
        chain: Chain::Tron,
        network_id: "0x2b6653dc",
        denom: None,
        slip44: 195,
        chain_type: ChainType::Tron,
        default_asset_type: Some(AssetType::TRC20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 3_000,
        rank: 70,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: None,
        stake: Some(StakeChainConfig {
            lock_time: 1_209_600,
            min_stake_amount: 1_000_000,
            change_amount_on_unstake: true,
            can_redelegate: true,
            can_withdraw: true,
            can_claim_rewards: true,
            reserved_for_fees: 10_000_000,
        }),
    },
    ChainConfig {
        chain: Chain::Doge,
        network_id: "1a91e3dace36e2be3bf030a65679fe821aa1d6ef92e7c9902eb318182c355691",
        denom: None,
        slip44: 3,
        chain_type: ChainType::Bitcoin,
        default_asset_type: None,
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 60_000,
        rank: 30,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: true,
        evm: None,
        stake: None,
    },
    ChainConfig {
        chain: Chain::Zcash,
        network_id: "00040fe8ec8471911baa1db1266ea15dd06b4a8a5c453883c000b031973dce08",
        denom: None,
        slip44: 133,
        chain_type: ChainType::Bitcoin,
        default_asset_type: None,
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 75_000,
        rank: 30,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: true,
        evm: None,
        stake: None,
    },
    ChainConfig {
        chain: Chain::Optimism,
        network_id: "10",
        denom: None,
        slip44: 60,
        chain_type: ChainType::Ethereum,
        default_asset_type: Some(AssetType::ERC20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 2_000,
        rank: 30,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: Some(EvmChainConfig {
            min_priority_fee: 1_000_000,
            chain_stack: ChainStack::Optimism,
            is_ethereum_layer2: true,
            weth_contract: Some(WETH_OP_CONTRACT),
        }),
        stake: None,
    },
    ChainConfig {
        chain: Chain::Aptos,
        network_id: "1",
        denom: Some("0x1::aptos_coin::AptosCoin"),
        slip44: 637,
        chain_type: ChainType::Aptos,
        default_asset_type: Some(AssetType::TOKEN),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 500,
        rank: 40,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: None,
        stake: Some(StakeChainConfig {
            lock_time: 2_592_000,
            min_stake_amount: 1_100_000_000,
            change_amount_on_unstake: false,
            can_redelegate: false,
            can_withdraw: true,
            can_claim_rewards: false,
            reserved_for_fees: 1_000_000,
        }),
    },
    ChainConfig {
        chain: Chain::Base,
        network_id: "8453",
        denom: None,
        slip44: 60,
        chain_type: ChainType::Ethereum,
        default_asset_type: Some(AssetType::ERC20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 2_000,
        rank: 30,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: Some(EvmChainConfig {
            min_priority_fee: 5_000_000,
            chain_stack: ChainStack::Optimism,
            is_ethereum_layer2: true,
            weth_contract: Some(WETH_BASE_CONTRACT),
        }),
        stake: None,
    },
    ChainConfig {
        chain: Chain::AvalancheC,
        network_id: "43114",
        denom: None,
        slip44: 9005,
        chain_type: ChainType::Ethereum,
        default_asset_type: Some(AssetType::ERC20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 2_000,
        rank: 30,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: Some(EvmChainConfig {
            min_priority_fee: 25_000_000_000,
            chain_stack: ChainStack::Native,
            is_ethereum_layer2: false,
            weth_contract: Some("0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7"),
        }),
        stake: None,
    },
    ChainConfig {
        chain: Chain::Sui,
        network_id: "35834a8a",
        denom: Some("0x2::sui::SUI"),
        slip44: 784,
        chain_type: ChainType::Sui,
        default_asset_type: Some(AssetType::TOKEN),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 500,
        rank: 40,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: None,
        stake: Some(StakeChainConfig {
            lock_time: 86_400,
            min_stake_amount: 1_000_000_000,
            change_amount_on_unstake: false,
            can_redelegate: false,
            can_withdraw: false,
            can_claim_rewards: false,
            reserved_for_fees: 100_000_000,
        }),
    },
    ChainConfig {
        chain: Chain::Xrp,
        network_id: "",
        denom: None,
        slip44: 144,
        chain_type: ChainType::Xrp,
        default_asset_type: None,
        account_activation_fee: Some(1_000_000),
        token_activation_fee: Some(200_000),
        minimum_account_balance: None,
        block_time: 4_000,
        rank: 40,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: None,
        stake: None,
    },
    ChainConfig {
        chain: Chain::OpBNB,
        network_id: "204",
        denom: None,
        slip44: 60,
        chain_type: ChainType::Ethereum,
        default_asset_type: Some(AssetType::BEP20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 1_000,
        rank: 30,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: Some(EvmChainConfig {
            min_priority_fee: 1_000_000,
            chain_stack: ChainStack::Optimism,
            is_ethereum_layer2: false,
            weth_contract: Some(WETH_OPSTACK_CONTRACT),
        }),
        stake: None,
    },
    ChainConfig {
        chain: Chain::Fantom,
        network_id: "250",
        denom: None,
        slip44: 60,
        chain_type: ChainType::Ethereum,
        default_asset_type: Some(AssetType::ERC20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 1_000,
        rank: 30,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: Some(EvmChainConfig {
            min_priority_fee: 3_500_000_000,
            chain_stack: ChainStack::Native,
            is_ethereum_layer2: false,
            weth_contract: Some("0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83"),
        }),
        stake: None,
    },
    ChainConfig {
        chain: Chain::Gnosis,
        network_id: "100",
        denom: None,
        slip44: 60,
        chain_type: ChainType::Ethereum,
        default_asset_type: Some(AssetType::ERC20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 5_000,
        rank: 30,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: Some(EvmChainConfig {
            min_priority_fee: 3_000_000_000,
            chain_stack: ChainStack::Native,
            is_ethereum_layer2: false,
            weth_contract: Some("0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d"),
        }),
        stake: None,
    },
    ChainConfig {
        chain: Chain::Celestia,
        network_id: "celestia",
        denom: Some("utia"),
        slip44: 118,
        chain_type: ChainType::Cosmos,
        default_asset_type: None,
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 6_000,
        rank: 40,
        is_swap_supported: false,
        is_nft_supported: false,
        is_utxo: false,
        evm: None,
        stake: Some(StakeChainConfig {
            lock_time: 1_814_400,
            min_stake_amount: 0,
            change_amount_on_unstake: true,
            can_redelegate: true,
            can_withdraw: false,
            can_claim_rewards: true,
            reserved_for_fees: 100_000,
        }),
    },
    ChainConfig {
        chain: Chain::Injective,
        network_id: "injective-1",
        denom: Some("inj"),
        slip44: 60,
        chain_type: ChainType::Cosmos,
        default_asset_type: None,
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 6_000,
        rank: 40,
        is_swap_supported: false,
        is_nft_supported: false,
        is_utxo: false,
        evm: None,
        stake: Some(StakeChainConfig {
            lock_time: 1_814_400,
            min_stake_amount: 0,
            change_amount_on_unstake: true,
            can_redelegate: true,
            can_withdraw: false,
            can_claim_rewards: true,
            reserved_for_fees: 10_000_000_000_000_000,
        }),
    },
    ChainConfig {
        chain: Chain::Sei,
        network_id: "pacific-1",
        denom: Some("usei"),
        slip44: 118,
        chain_type: ChainType::Cosmos,
        default_asset_type: None,
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 1_000,
        rank: 30,
        is_swap_supported: false,
        is_nft_supported: false,
        is_utxo: false,
        evm: None,
        stake: Some(StakeChainConfig {
            lock_time: 1_814_400,
            min_stake_amount: 0,
            change_amount_on_unstake: true,
            can_redelegate: true,
            can_withdraw: false,
            can_claim_rewards: true,
            reserved_for_fees: 100_000,
        }),
    },
    ChainConfig {
        chain: Chain::Manta,
        network_id: "169",
        denom: None,
        slip44: 60,
        chain_type: ChainType::Ethereum,
        default_asset_type: Some(AssetType::ERC20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 2_000,
        rank: 30,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: Some(EvmChainConfig {
            min_priority_fee: 10_000_000,
            chain_stack: ChainStack::Native,
            is_ethereum_layer2: false,
            weth_contract: Some("0x0dc808adce2099a9f62aa87d9670745aba741746"),
        }),
        stake: None,
    },
    ChainConfig {
        chain: Chain::Blast,
        network_id: "81457",
        denom: None,
        slip44: 60,
        chain_type: ChainType::Ethereum,
        default_asset_type: Some(AssetType::ERC20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 2_000,
        rank: 30,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: Some(EvmChainConfig {
            min_priority_fee: 200_000_000,
            chain_stack: ChainStack::Native,
            is_ethereum_layer2: true,
            weth_contract: Some(WETH_BLAST_CONTRACT),
        }),
        stake: None,
    },
    ChainConfig {
        chain: Chain::Noble,
        network_id: "noble-1",
        denom: Some("uusdc"),
        slip44: 118,
        chain_type: ChainType::Cosmos,
        default_asset_type: None,
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 6_000,
        rank: 20,
        is_swap_supported: false,
        is_nft_supported: false,
        is_utxo: false,
        evm: None,
        stake: None,
    },
    ChainConfig {
        chain: Chain::ZkSync,
        network_id: "324",
        denom: None,
        slip44: 60,
        chain_type: ChainType::Ethereum,
        default_asset_type: Some(AssetType::ERC20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 1_000,
        rank: 30,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: Some(EvmChainConfig {
            min_priority_fee: 20_000_000,
            chain_stack: ChainStack::ZkSync,
            is_ethereum_layer2: true,
            weth_contract: Some(WETH_ZKSYNC_CONTRACT),
        }),
        stake: None,
    },
    ChainConfig {
        chain: Chain::Linea,
        network_id: "59144",
        denom: None,
        slip44: 60,
        chain_type: ChainType::Ethereum,
        default_asset_type: Some(AssetType::ERC20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 1_000,
        rank: 30,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: Some(EvmChainConfig {
            min_priority_fee: 50_000_000,
            chain_stack: ChainStack::Native,
            is_ethereum_layer2: true,
            weth_contract: Some(WETH_LINEA_CONTRACT),
        }),
        stake: None,
    },
    ChainConfig {
        chain: Chain::Mantle,
        network_id: "5000",
        denom: None,
        slip44: 60,
        chain_type: ChainType::Ethereum,
        default_asset_type: Some(AssetType::ERC20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 1_000,
        rank: 30,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: Some(EvmChainConfig {
            min_priority_fee: 10_000_000,
            chain_stack: ChainStack::Native,
            is_ethereum_layer2: true,
            weth_contract: Some("0x78c1b0C915c4FAA5FffA6CAbf0219DA63d7f4cb8"),
        }),
        stake: None,
    },
    ChainConfig {
        chain: Chain::Celo,
        network_id: "42220",
        denom: None,
        slip44: 60,
        chain_type: ChainType::Ethereum,
        default_asset_type: Some(AssetType::ERC20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 1_000,
        rank: 30,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: Some(EvmChainConfig {
            min_priority_fee: 10_000_000,
            chain_stack: ChainStack::Optimism,
            is_ethereum_layer2: true,
            weth_contract: Some("0x471EcE3750Da237f93B8E339c536989b8978a438"),
        }),
        stake: None,
    },
    ChainConfig {
        chain: Chain::Near,
        network_id: "mainnet",
        denom: None,
        slip44: 397,
        chain_type: ChainType::Near,
        default_asset_type: None,
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 1_000,
        rank: 30,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: None,
        stake: None,
    },
    ChainConfig {
        chain: Chain::World,
        network_id: "480",
        denom: None,
        slip44: 60,
        chain_type: ChainType::Ethereum,
        default_asset_type: Some(AssetType::ERC20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 2_000,
        rank: 30,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: Some(EvmChainConfig {
            min_priority_fee: 1_000_000,
            chain_stack: ChainStack::Optimism,
            is_ethereum_layer2: true,
            weth_contract: Some(WETH_WORLD_CONTRACT),
        }),
        stake: None,
    },
    ChainConfig {
        chain: Chain::Stellar,
        network_id: "Public Global Stellar Network ; September 2015",
        denom: None,
        slip44: 148,
        chain_type: ChainType::Stellar,
        default_asset_type: None,
        account_activation_fee: Some(10_000_000),
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 6_000,
        rank: 30,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: None,
        stake: None,
    },
    ChainConfig {
        chain: Chain::Sonic,
        network_id: "146",
        denom: None,
        slip44: 60,
        chain_type: ChainType::Ethereum,
        default_asset_type: Some(AssetType::ERC20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 500,
        rank: 30,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: Some(EvmChainConfig {
            min_priority_fee: 10_000_000,
            chain_stack: ChainStack::Native,
            is_ethereum_layer2: false,
            weth_contract: Some("0x039e2fB66102314Ce7b64Ce5Ce3E5183bc94aD38"),
        }),
        stake: None,
    },
    ChainConfig {
        chain: Chain::Algorand,
        network_id: "mainnet-v1.0",
        denom: None,
        slip44: 283,
        chain_type: ChainType::Algorand,
        default_asset_type: Some(AssetType::ASA),
        account_activation_fee: Some(100_000),
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 4_000,
        rank: 30,
        is_swap_supported: false,
        is_nft_supported: false,
        is_utxo: false,
        evm: None,
        stake: None,
    },
    ChainConfig {
        chain: Chain::Polkadot,
        network_id: "Polkadot Asset Hub",
        denom: None,
        slip44: 354,
        chain_type: ChainType::Polkadot,
        default_asset_type: None,
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: Some(10_000_000_000),
        block_time: 5_000,
        rank: 40,
        is_swap_supported: false,
        is_nft_supported: false,
        is_utxo: false,
        evm: None,
        stake: None,
    },
    ChainConfig {
        chain: Chain::Plasma,
        network_id: "9745",
        denom: None,
        slip44: 60,
        chain_type: ChainType::Ethereum,
        default_asset_type: Some(AssetType::ERC20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 2_000,
        rank: 30,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: Some(EvmChainConfig {
            min_priority_fee: 100_000,
            chain_stack: ChainStack::Native,
            is_ethereum_layer2: false,
            weth_contract: Some("0x6100E367285b01F48D07953803A2d8dCA5D19873"),
        }),
        stake: None,
    },
    ChainConfig {
        chain: Chain::Cardano,
        network_id: "764824073",
        denom: None,
        slip44: 1_815,
        chain_type: ChainType::Cardano,
        default_asset_type: None,
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 20_000,
        rank: 30,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: true,
        evm: None,
        stake: None,
    },
    ChainConfig {
        chain: Chain::Abstract,
        network_id: "2741",
        denom: None,
        slip44: 60,
        chain_type: ChainType::Ethereum,
        default_asset_type: Some(AssetType::ERC20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 1_000,
        rank: 35,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: Some(EvmChainConfig {
            min_priority_fee: 1_000_000,
            chain_stack: ChainStack::ZkSync,
            is_ethereum_layer2: true,
            weth_contract: Some("0x3439153EB7AF838Ad19d56E1571FBD09333C2809"),
        }),
        stake: None,
    },
    ChainConfig {
        chain: Chain::Berachain,
        network_id: "80094",
        denom: None,
        slip44: 60,
        chain_type: ChainType::Ethereum,
        default_asset_type: Some(AssetType::ERC20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 2_000,
        rank: 35,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: Some(EvmChainConfig {
            min_priority_fee: 1_000_000_000,
            chain_stack: ChainStack::Native,
            is_ethereum_layer2: false,
            weth_contract: Some("0x6969696969696969696969696969696969696969"),
        }),
        stake: None,
    },
    ChainConfig {
        chain: Chain::Ink,
        network_id: "57073",
        denom: None,
        slip44: 60,
        chain_type: ChainType::Ethereum,
        default_asset_type: Some(AssetType::ERC20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 1_000,
        rank: 35,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: Some(EvmChainConfig {
            min_priority_fee: 1_000_000,
            chain_stack: ChainStack::Optimism,
            is_ethereum_layer2: true,
            weth_contract: Some(WETH_INK_CONTRACT),
        }),
        stake: None,
    },
    ChainConfig {
        chain: Chain::Unichain,
        network_id: "130",
        denom: None,
        slip44: 60,
        chain_type: ChainType::Ethereum,
        default_asset_type: Some(AssetType::ERC20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 1_000,
        rank: 35,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: Some(EvmChainConfig {
            min_priority_fee: 1_000_000,
            chain_stack: ChainStack::Optimism,
            is_ethereum_layer2: true,
            weth_contract: Some(WETH_UNICHAIN_CONTRACT),
        }),
        stake: None,
    },
    ChainConfig {
        chain: Chain::Hyperliquid,
        network_id: "999",
        denom: None,
        slip44: 60,
        chain_type: ChainType::Ethereum,
        default_asset_type: Some(AssetType::ERC20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 2_000,
        rank: 40,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: Some(EvmChainConfig {
            min_priority_fee: 1_000_000_000,
            chain_stack: ChainStack::Native,
            is_ethereum_layer2: false,
            weth_contract: Some("0x5555555555555555555555555555555555555555"),
        }),
        stake: None,
    },
    ChainConfig {
        chain: Chain::HyperCore,
        network_id: "1337",
        denom: None,
        slip44: 60,
        chain_type: ChainType::HyperCore,
        default_asset_type: Some(AssetType::ERC20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 2_000,
        rank: 40,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: None,
        stake: Some(StakeChainConfig {
            lock_time: 604_800,
            min_stake_amount: 1_000_000,
            change_amount_on_unstake: true,
            can_redelegate: false,
            can_withdraw: false,
            can_claim_rewards: false,
            reserved_for_fees: 0,
        }),
    },
    ChainConfig {
        chain: Chain::Monad,
        network_id: "143",
        denom: None,
        slip44: 60,
        chain_type: ChainType::Ethereum,
        default_asset_type: Some(AssetType::ERC20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 500,
        rank: 40,
        is_swap_supported: true,
        is_nft_supported: false,
        is_utxo: false,
        evm: Some(EvmChainConfig {
            min_priority_fee: 1_000_000_000,
            chain_stack: ChainStack::Native,
            is_ethereum_layer2: false,
            weth_contract: Some("0x3bd359C1119dA7Da1D913D1C4D2B7c461115433A"),
        }),
        stake: Some(StakeChainConfig {
            lock_time: 86_400,
            min_stake_amount: 100_000_000_000_000_000,
            change_amount_on_unstake: true,
            can_redelegate: false,
            can_withdraw: true,
            can_claim_rewards: true,
            reserved_for_fees: 50_000_000_000_000_000,
        }),
    },
    ChainConfig {
        chain: Chain::XLayer,
        network_id: "196",
        denom: None,
        slip44: 60,
        chain_type: ChainType::Ethereum,
        default_asset_type: Some(AssetType::ERC20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 2_000,
        rank: 30,
        is_swap_supported: false,
        is_nft_supported: false,
        is_utxo: false,
        evm: Some(EvmChainConfig {
            min_priority_fee: 1_000_000_000,
            chain_stack: ChainStack::Native,
            is_ethereum_layer2: true,
            weth_contract: Some("0xe538905cf8410324e03a5a23c1c177a474d59b2b"),
        }),
        stake: None,
    },
    ChainConfig {
        chain: Chain::Stable,
        network_id: "988",
        denom: None,
        slip44: 60,
        chain_type: ChainType::Ethereum,
        default_asset_type: Some(AssetType::ERC20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 1_000,
        rank: 30,
        is_swap_supported: false,
        is_nft_supported: false,
        is_utxo: false,
        evm: Some(EvmChainConfig {
            min_priority_fee: 1_000_000,
            chain_stack: ChainStack::Native,
            is_ethereum_layer2: false,
            weth_contract: Some("0x779Ded0c9e1022225f8E0630b35a9b54bE713736"),
        }),
        stake: None,
    },
    ChainConfig {
        chain: Chain::Rootstock,
        network_id: "30",
        denom: None,
        slip44: 137,
        chain_type: ChainType::Ethereum,
        default_asset_type: Some(AssetType::ERC20),
        account_activation_fee: None,
        token_activation_fee: None,
        minimum_account_balance: None,
        block_time: 25_000,
        rank: 31,
        is_swap_supported: false,
        is_nft_supported: false,
        is_utxo: false,
        evm: Some(EvmChainConfig {
            min_priority_fee: 0,
            chain_stack: ChainStack::Native,
            is_ethereum_layer2: false,
            weth_contract: Some("0x3b3dd26c5cd371c707cc64b864f11d44692c505d"),
        }),
        stake: None,
    },
];

pub fn get_chain_config(chain: Chain) -> &'static ChainConfig {
    CHAIN_CONFIGS
        .iter()
        .find(|config| config.chain == chain)
        .unwrap_or_else(|| panic!("Missing chain config for {chain}"))
}
