use serde::{Deserialize, Serialize};
use strum::{AsRefStr, EnumIter, EnumString, IntoEnumIterator};

#[derive(Debug, Clone, Serialize, Deserialize, AsRefStr, EnumString, EnumIter, PartialEq, Eq, Hash)]
#[strum(serialize_all = "camelCase")]
pub enum ConfigKey {
    // Referral
    ReferralPerDeviceDaily,
    ReferralPerIpDaily,
    ReferralPerIpWeekly,
    ReferralPerCountryDaily,
    ReferralPerUserDaily,
    ReferralPerUserWeekly,
    ReferralPerUserHourly,
    ReferralVerifiedMultiplier,
    ReferralTrustedMultiplier,
    ReferralCooldown,
    ReferralUseDailyLimit,
    ReferralIneligibleCountries,
    ReferralVerificationDelay,
    ReferralEligibility,

    // Username
    UsernameCreationPerIp,
    UsernameCreationPerDevice,
    UsernameCreationGlobalDailyLimit,
    UsernameCreationPerCountryDailyLimit,

    // Redemption
    RedemptionPerUserDaily,
    RedemptionPerUserWeekly,
    RedemptionMinAccountAge,
    RedemptionCooldownAfterReferral,
    RedemptionRetryMaxRetries,
    RedemptionRetryDelay,
    RedemptionRetryErrors,

    // Referral IP
    ReferralIpConfidenceScoreThreshold,
    ReferralBlockedIpTypes,
    ReferralBlockedIpTypePenalty,
    ReferralMaxAbuseScore,
    ReferralPenaltyIsps,
    ReferralPenaltyIspsScore,
    ReferralIpTorAllowed,

    // Referral Risk Scoring (global cross-referrer penalties)
    ReferralRiskScoreFingerprintMatchPerReferrer,
    ReferralRiskScoreFingerprintMatchMaxPenalty,
    ReferralRiskScoreIpReuse,
    ReferralRiskScoreIspModelMatch,
    ReferralRiskScoreDeviceIdReusePerReferrer,
    ReferralRiskScoreDeviceIdReuseMaxPenalty,
    ReferralRiskScoreIneligibleIpType,
    ReferralRiskScoreVerifiedUserReduction,
    ReferralRiskScoreEarlyReferralReductionInitial,
    ReferralRiskScoreEarlyReferralReductionStep,
    ReferralRiskScoreMaxAllowed,
    ReferralRiskScoreLookback,
    ReferralRiskScoreSameReferrerPatternThreshold,
    ReferralRiskScoreSameReferrerPatternPenalty,
    ReferralRiskScoreSameReferrerFingerprintThreshold,
    ReferralRiskScoreSameReferrerFingerprintPenalty,
    ReferralRiskScoreSameReferrerDeviceModelThreshold,
    ReferralRiskScoreSameReferrerDeviceModelPenalty,
    ReferralRiskScoreDeviceModelRingThreshold,
    ReferralRiskScoreDeviceModelRingPenaltyPerMember,
    ReferralRiskScoreHighRiskPlatformStores,
    ReferralRiskScoreHighRiskPlatformStorePenalty,
    ReferralRiskScoreHighRiskCountries,
    ReferralRiskScoreHighRiskCountryPenalty,
    ReferralRiskScoreHighRiskLocales,
    ReferralRiskScoreHighRiskLocalePenalty,
    ReferralRiskScoreHighRiskDeviceModels,
    ReferralRiskScoreHighRiskDeviceModelPenalty,
    ReferralRiskScoreHighRiskUserAgents,
    ReferralRiskScoreHighRiskUserAgentPenalty,
    ReferralRiskScoreIpHistoryPenaltyPerAbuser,
    ReferralRiskScoreIpHistoryMaxPenalty,
    ReferralRiskScoreCrossReferrerDevicePenalty,
    ReferralRiskScoreCrossReferrerFingerprintThreshold,
    ReferralRiskScoreCrossReferrerFingerprintPenalty,
    ReferralRiskScoreCountryDiversityThreshold,
    ReferralRiskScoreCountryDiversityPenaltyPerCountry,
    ReferralRiskScoreDeviceFarmingThreshold,
    ReferralRiskScoreDeviceFarmingPenaltyPerDevice,

    // Referral Abuse Detection
    ReferralAbuseDisableThreshold,
    ReferralAbuseAttemptPenalty,
    ReferralAbuseVerifiedThresholdMultiplier,
    ReferralAbuseLookback,
    ReferralAbuseMinReferralsToEvaluate,

    ReferralAbuseCountryRotationThreshold,
    ReferralAbuseCountryRotationPenalty,
    ReferralAbuseRingReferrersPerDeviceThreshold,
    ReferralAbuseRingReferrersPerFingerprintThreshold,
    ReferralAbuseRingPenalty,
    ReferralAbuseDeviceFarmingThreshold,
    ReferralAbuseDeviceFarmingPenalty,
    ReferralAbuseVelocityWindow,
    ReferralAbuseVelocityDivisor,
    ReferralAbuseVelocityPenaltyPerSignal,
    ReferralAbuseDisabledReferrerPenalty,

    // Fiat
    FiatValidateSubscription,

    // Transactions
    TransactionsMinAmountUsd,
    TransactionsOutdatedBlockCount,
    TransactionsOutdatedMinTimeout,

    // Alerter
    AlerterPriceAlertsTimer,
    AlerterPriceAlertsCooldown,
    AlerterPriceAlertsThreshold,
    AlerterPriceAlertsRankDivisor,
    AlerterPriceAlertsMilestones,
    AlerterStakeRewardsTimer,
    AlerterStakeRewardsThreshold,
    AlerterStakeRewardsLookback,

    // Price
    PriceTimerTopMarketCap,
    PriceTimerHighMarketCap,
    PriceTimerLowMarketCap,
    PriceTimerFiatRates,
    PriceTimerChartsHourly,
    PriceTimerChartsDaily,
    PriceTimerMarkets,
    PriceTimerCleanOutdated,
    PriceTimerCleanupChartsHourly,
    PriceOutdated,

    // Assets
    AssetsTimerUpdateSuspicious,
    AssetsTimerUpdateStakeApy,
    AssetsTimerUpdatePerpetuals,
    AssetsTimerUpdateUsageRank,
    AssetsTimerUpdateImages,
    AssetsTimerUpdateHasPrice,

    // Fiat
    FiatTimerUpdateAssets,
    FiatTimerUpdateProviderCountries,
    FiatTimerUpdateBuyableAssets,
    FiatTimerUpdateSellableAssets,
    FiatTimerUpdateTrending,

    // Scan
    ScanTimerUpdateValidators,
    ScanTimerUpdateValidatorsStatic,

    // Rewards
    RewardsTimerAbuseChecker,
    RewardsTimerEligibilityChecker,
    RewardsEligibilityActiveDuration,
    RewardsEligibilityTransactionsCount,
    RewardsEligibilityPromotionLimit,

    // Device
    DeviceTimerUpdater,
    DeviceTimerInactiveObserver,

    // Version
    VersionTimerUpdateStoreVersions,

    // Transaction
    TransactionTimerCleanup,
    TransactionTimerInTransitUpdate,
    TransactionTimerPendingUpdate,
    TransactionInTransitTimeout,
    TransactionInTransitQueryLimit,
    TransactionSwapOutdatedTimeout,
    TransactionCleanupAddressMaxCount,
    TransactionCleanupAddressLimit,
    TransactionCleanupLookback,

    // Perpetuals
    PerpetualClassifierInterval,
    PerpetualObserverInterval,
    PerpetualAddressRefreshInterval,
    PerpetualPriorityObserverInterval,
    PerpetualPriorityTriggerBps,
    PerpetualPriorityLiquidationBps,

    // Search
    SearchAssetsUpdateInterval,
    SearchPerpetualsUpdateInterval,
    SearchNftsUpdateInterval,
    SearchAssetsLastUpdatedAt,
    SearchPerpetualsLastUpdatedAt,
    SearchNftsLastUpdatedAt,

    // Parser
    ParserCatchupReloadInterval,
    ParserMinCheckInterval,
    ParserMaxCheckInterval,
    ParserErrorInterval,

    // Price Observed (WebSocket)
    PriceObservedFetchInterval,
    PriceObservedMaxAssets,
    PriceObservedMinObservers,

    // Support Bot
    SupportBotSystemPrompt,
    SupportBotMaxTokens,
    SupportBotModel,
    SupportBotApiVersion,
}

impl ConfigKey {
    pub fn all() -> Vec<Self> {
        Self::iter().collect()
    }

    pub fn default_value(&self) -> &'static str {
        match self {
            Self::ReferralPerDeviceDaily => "1",
            Self::ReferralPerIpDaily => "3",
            Self::ReferralPerIpWeekly => "10",
            Self::ReferralPerCountryDaily => "100",
            Self::ReferralPerUserDaily => "5",
            Self::ReferralPerUserWeekly => "15",
            Self::ReferralPerUserHourly => "2",
            Self::ReferralVerifiedMultiplier => "2",
            Self::ReferralTrustedMultiplier => "3",
            Self::ReferralCooldown => "1m",
            Self::ReferralUseDailyLimit => "1000",
            Self::ReferralIneligibleCountries => "[]",
            Self::ReferralVerificationDelay => "24h",
            Self::ReferralEligibility => "7d",
            Self::UsernameCreationPerIp => "10",
            Self::UsernameCreationPerDevice => "1",
            Self::UsernameCreationGlobalDailyLimit => "1000",
            Self::UsernameCreationPerCountryDailyLimit => "100",
            Self::RedemptionPerUserDaily => "1",
            Self::RedemptionPerUserWeekly => "3",
            Self::RedemptionMinAccountAge => "1h",
            Self::RedemptionCooldownAfterReferral => "1m",
            Self::RedemptionRetryMaxRetries => "1",
            Self::RedemptionRetryDelay => "15s",
            Self::RedemptionRetryErrors => r#"["transaction gas price below minimum"]"#,
            Self::ReferralIpConfidenceScoreThreshold => "10",
            Self::ReferralBlockedIpTypes => r#"["dataCenter", "hosting"]"#,
            Self::ReferralBlockedIpTypePenalty => "100",
            Self::ReferralMaxAbuseScore => "60",
            Self::ReferralPenaltyIsps => r#"[]"#,
            Self::ReferralPenaltyIspsScore => "30",
            Self::ReferralIpTorAllowed => "false",
            Self::ReferralRiskScoreFingerprintMatchPerReferrer => "50",
            Self::ReferralRiskScoreFingerprintMatchMaxPenalty => "200",
            Self::ReferralRiskScoreIpReuse => "50",
            Self::ReferralRiskScoreIspModelMatch => "30",
            Self::ReferralRiskScoreDeviceIdReusePerReferrer => "50",
            Self::ReferralRiskScoreDeviceIdReuseMaxPenalty => "200",
            Self::ReferralRiskScoreIneligibleIpType => "100",
            Self::ReferralRiskScoreVerifiedUserReduction => "20",
            Self::ReferralRiskScoreEarlyReferralReductionInitial => "20",
            Self::ReferralRiskScoreEarlyReferralReductionStep => "10",
            Self::ReferralRiskScoreMaxAllowed => "60",
            Self::ReferralRiskScoreLookback => "90d",
            Self::ReferralRiskScoreSameReferrerPatternThreshold => "3",
            Self::ReferralRiskScoreSameReferrerPatternPenalty => "40",
            Self::ReferralRiskScoreSameReferrerFingerprintThreshold => "2",
            Self::ReferralRiskScoreSameReferrerFingerprintPenalty => "60",
            Self::ReferralRiskScoreSameReferrerDeviceModelThreshold => "3",
            Self::ReferralRiskScoreSameReferrerDeviceModelPenalty => "50",
            Self::ReferralRiskScoreDeviceModelRingThreshold => "2",
            Self::ReferralRiskScoreDeviceModelRingPenaltyPerMember => "40",
            Self::ReferralRiskScoreHighRiskPlatformStores => "[]",
            Self::ReferralRiskScoreHighRiskPlatformStorePenalty => "20",
            Self::ReferralRiskScoreHighRiskCountries => "[]",
            Self::ReferralRiskScoreHighRiskCountryPenalty => "15",
            Self::ReferralRiskScoreHighRiskLocales => "[]",
            Self::ReferralRiskScoreHighRiskLocalePenalty => "10",
            Self::ReferralRiskScoreHighRiskDeviceModels => r#"["sdk_gphone", "(?i)emulator", "(?i)simulator"]"#,
            Self::ReferralRiskScoreHighRiskDeviceModelPenalty => "50",
            Self::ReferralRiskScoreHighRiskUserAgents => r#"["(?i)python", "(?i)curl", "(?i)httpie", "(?i)postman", "(?i)insomnia"]"#,
            Self::ReferralRiskScoreHighRiskUserAgentPenalty => "100",
            Self::ReferralRiskScoreIpHistoryPenaltyPerAbuser => "30",
            Self::ReferralRiskScoreIpHistoryMaxPenalty => "150",
            Self::ReferralRiskScoreCrossReferrerDevicePenalty => "500",
            Self::ReferralRiskScoreCrossReferrerFingerprintThreshold => "2",
            Self::ReferralRiskScoreCrossReferrerFingerprintPenalty => "100",
            Self::ReferralRiskScoreCountryDiversityThreshold => "5",
            Self::ReferralRiskScoreCountryDiversityPenaltyPerCountry => "5",
            Self::ReferralRiskScoreDeviceFarmingThreshold => "10",
            Self::ReferralRiskScoreDeviceFarmingPenaltyPerDevice => "3",
            Self::ReferralAbuseDisableThreshold => "200",
            Self::ReferralAbuseAttemptPenalty => "15",
            Self::ReferralAbuseVerifiedThresholdMultiplier => "2",
            Self::ReferralAbuseLookback => "7d",
            Self::ReferralAbuseMinReferralsToEvaluate => "2",
            Self::ReferralAbuseCountryRotationThreshold => "2",
            Self::ReferralAbuseCountryRotationPenalty => "50",
            Self::ReferralAbuseRingReferrersPerDeviceThreshold => "2",
            Self::ReferralAbuseRingReferrersPerFingerprintThreshold => "2",
            Self::ReferralAbuseRingPenalty => "80",
            Self::ReferralAbuseDeviceFarmingThreshold => "5",
            Self::ReferralAbuseDeviceFarmingPenalty => "10",
            Self::ReferralAbuseVelocityWindow => "5m",
            Self::ReferralAbuseVelocityDivisor => "2",
            Self::ReferralAbuseVelocityPenaltyPerSignal => "100",
            Self::ReferralAbuseDisabledReferrerPenalty => "80",
            Self::FiatValidateSubscription => "false",
            Self::TransactionsMinAmountUsd => "0.05",
            Self::TransactionsOutdatedBlockCount => "12",
            Self::TransactionsOutdatedMinTimeout => "15m",
            Self::AlerterPriceAlertsTimer => "60s",
            Self::AlerterPriceAlertsCooldown => "24h",
            Self::AlerterPriceAlertsThreshold => "5.0",
            Self::AlerterPriceAlertsRankDivisor => "5.0",
            Self::AlerterPriceAlertsMilestones => "[1, 5, 10, 50, 100, 500, 1000, 5000, 10000, 50000, 100000, 500000, 1000000]",
            Self::PriceTimerTopMarketCap => "60s",
            Self::PriceTimerHighMarketCap => "5m",
            Self::PriceTimerLowMarketCap => "15m",
            Self::PriceTimerFiatRates => "6m",
            Self::PriceTimerChartsHourly => "60s",
            Self::PriceTimerChartsDaily => "6m",
            Self::PriceTimerMarkets => "1h",
            Self::PriceTimerCleanOutdated => "1d",
            Self::PriceTimerCleanupChartsHourly => "1d",
            Self::PriceOutdated => "7d",
            Self::AssetsTimerUpdateSuspicious => "1h",
            Self::AssetsTimerUpdateStakeApy => "1d",
            Self::AssetsTimerUpdatePerpetuals => "1h",
            Self::AssetsTimerUpdateUsageRank => "1h",
            Self::AssetsTimerUpdateImages => "8h",
            Self::AssetsTimerUpdateHasPrice => "1h",
            Self::FiatTimerUpdateAssets => "1h",
            Self::FiatTimerUpdateProviderCountries => "1h",
            Self::FiatTimerUpdateBuyableAssets => "1h",
            Self::FiatTimerUpdateSellableAssets => "1h",
            Self::FiatTimerUpdateTrending => "1h",
            Self::ScanTimerUpdateValidators => "1d",
            Self::ScanTimerUpdateValidatorsStatic => "1h",
            Self::RewardsTimerAbuseChecker => "60s",
            Self::RewardsTimerEligibilityChecker => "60s",
            Self::RewardsEligibilityActiveDuration => "7d",
            Self::RewardsEligibilityTransactionsCount => "3",
            Self::RewardsEligibilityPromotionLimit => "1",
            Self::AlerterStakeRewardsTimer => "6h",
            Self::AlerterStakeRewardsThreshold => "0.01",
            Self::AlerterStakeRewardsLookback => "30d",
            Self::DeviceTimerUpdater => "1d",
            Self::DeviceTimerInactiveObserver => "1d",
            Self::VersionTimerUpdateStoreVersions => "1h",
            Self::TransactionTimerCleanup => "1d",
            Self::TransactionTimerInTransitUpdate => "60s",
            Self::TransactionTimerPendingUpdate => "30s",
            Self::TransactionInTransitTimeout => "12h",
            Self::TransactionInTransitQueryLimit => "100",
            Self::TransactionSwapOutdatedTimeout => "2h",
            Self::TransactionCleanupAddressMaxCount => "5000",
            Self::TransactionCleanupAddressLimit => "200",
            Self::TransactionCleanupLookback => "90d",
            Self::PerpetualClassifierInterval => "15m",
            Self::PerpetualObserverInterval => "1m",
            Self::PerpetualAddressRefreshInterval => "1h",
            Self::PerpetualPriorityObserverInterval => "10s",
            Self::PerpetualPriorityTriggerBps => "100",
            Self::PerpetualPriorityLiquidationBps => "300",
            Self::SearchAssetsUpdateInterval => "30m",
            Self::SearchPerpetualsUpdateInterval => "30m",
            Self::SearchNftsUpdateInterval => "30m",
            Self::SearchAssetsLastUpdatedAt => "0",
            Self::SearchPerpetualsLastUpdatedAt => "0",
            Self::SearchNftsLastUpdatedAt => "0",
            Self::ParserCatchupReloadInterval => "50",
            Self::ParserMinCheckInterval => "1s",
            Self::ParserMaxCheckInterval => "8s",
            Self::ParserErrorInterval => "30s",
            Self::PriceObservedFetchInterval => "30s",
            Self::PriceObservedMaxAssets => "100",
            Self::PriceObservedMinObservers => "2",
            Self::SupportBotSystemPrompt => "",
            Self::SupportBotMaxTokens => "1024",
            Self::SupportBotModel => "claude-sonnet-4-6",
            Self::SupportBotApiVersion => "2023-06-01",
        }
    }
}
