macro_rules! with_evm_chain_list {
    ($macro:ident) => {
        $macro! {
            Ethereum {
                chain_id: "1",
                rpc_urls: ["https://eth-pokt.nodies.app"],
                native_name: "Ethereum",
                native_symbol: "ETH",
                native_decimals: 18,
                default_asset_type: AssetType::ERC20,
                slip44: 60,
                block_time_ms: 12_000,
                rank: 85,
                swap_supported: true,
                chain_stack: ChainStack::Native,
                min_priority_fee: 100_000_000,
                is_ethereum_layer2: false,
                weth_contract: Some("0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
            },
            SmartChain {
                chain_id: "56",
                rpc_urls: ["https://bsc-dataseed1.bnbchain.org"],
                native_name: "BNB Chain",
                native_symbol: "BNB",
                native_decimals: 18,
                default_asset_type: AssetType::BEP20,
                slip44: 9006,
                block_time_ms: 1_000,
                rank: 80,
                swap_supported: true,
                chain_stack: ChainStack::Native,
                min_priority_fee: 50_000_000,
                is_ethereum_layer2: false,
                weth_contract: Some("0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c"),
            },
            Polygon {
                chain_id: "137",
                rpc_urls: ["https://polygon.llamarpc.com"],
                native_name: "Polygon",
                native_symbol: "POL",
                native_decimals: 18,
                default_asset_type: AssetType::ERC20,
                slip44: 60,
                block_time_ms: 3_000,
                rank: 30,
                swap_supported: true,
                chain_stack: ChainStack::Native,
                min_priority_fee: 30_000_000_000,
                is_ethereum_layer2: false,
                weth_contract: Some("0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270"),
            },
            Plasma {
                chain_id: "9745",
                rpc_urls: ["https://rpc.plasma.to"],
                native_name: "Plasma",
                native_symbol: "XPL",
                native_decimals: 18,
                default_asset_type: AssetType::ERC20,
                slip44: 60,
                block_time_ms: 2_000,
                rank: 30,
                swap_supported: true,
                chain_stack: ChainStack::Native,
                min_priority_fee: 100_000,
                is_ethereum_layer2: false,
                weth_contract: Some("0x6100E367285b01F48D07953803A2d8dCA5D19873"),
            },
            Arbitrum {
                chain_id: "42161",
                rpc_urls: ["https://arb1.arbitrum.io/rpc"],
                native_name: "Arbitrum ETH",
                native_symbol: "ETH",
                native_decimals: 18,
                default_asset_type: AssetType::ERC20,
                slip44: 60,
                block_time_ms: 1_000,
                rank: 30,
                swap_supported: true,
                chain_stack: ChainStack::Native,
                min_priority_fee: 10_000_000,
                is_ethereum_layer2: true,
                weth_contract: Some("0x82aF49447D8a07e3bd95BD0d56f35241523fBab1"),
            },
            Optimism {
                chain_id: "10",
                rpc_urls: ["https://mainnet.optimism.io"],
                native_name: "Optimism ETH",
                native_symbol: "ETH",
                native_decimals: 18,
                default_asset_type: AssetType::ERC20,
                slip44: 60,
                block_time_ms: 2_000,
                rank: 30,
                swap_supported: true,
                chain_stack: ChainStack::Optimism,
                min_priority_fee: 1_000_000,
                is_ethereum_layer2: true,
                weth_contract: Some("0x4200000000000000000000000000000000000006"),
            },
            Base {
                chain_id: "8453",
                rpc_urls: ["https://mainnet.base.org"],
                native_name: "Base ETH",
                native_symbol: "ETH",
                native_decimals: 18,
                default_asset_type: AssetType::ERC20,
                slip44: 60,
                block_time_ms: 2_000,
                rank: 30,
                swap_supported: true,
                chain_stack: ChainStack::Optimism,
                min_priority_fee: 5_000_000,
                is_ethereum_layer2: true,
                weth_contract: Some("0x4200000000000000000000000000000000000006"),
            },
            AvalancheC {
                chain_id: "43114",
                rpc_urls: ["https://api.avax.network/ext/bc/C/rpc"],
                native_name: "Avalanche",
                native_symbol: "AVAX",
                native_decimals: 18,
                default_asset_type: AssetType::ERC20,
                slip44: 9005,
                block_time_ms: 2_000,
                rank: 30,
                swap_supported: true,
                chain_stack: ChainStack::Native,
                min_priority_fee: 25_000_000_000,
                is_ethereum_layer2: false,
                weth_contract: Some("0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7"),
            },
            OpBNB {
                chain_id: "204",
                rpc_urls: ["https://opbnb-mainnet-rpc.bnbchain.org"],
                native_name: "opBNB",
                native_symbol: "BNB",
                native_decimals: 18,
                default_asset_type: AssetType::BEP20,
                slip44: 60,
                block_time_ms: 1_000,
                rank: 30,
                swap_supported: true,
                chain_stack: ChainStack::Optimism,
                min_priority_fee: 1_000_000,
                is_ethereum_layer2: false,
                weth_contract: Some("0x4200000000000000000000000000000000000006"),
            },
            Fantom {
                chain_id: "250",
                rpc_urls: ["https://fantom.publicnode.com"],
                native_name: "Fantom",
                native_symbol: "FTM",
                native_decimals: 18,
                default_asset_type: AssetType::ERC20,
                slip44: 60,
                block_time_ms: 1_000,
                rank: 30,
                swap_supported: true,
                chain_stack: ChainStack::Native,
                min_priority_fee: 3_500_000_000,
                is_ethereum_layer2: false,
                weth_contract: Some("0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83"),
            },
            Gnosis {
                chain_id: "100",
                rpc_urls: ["https://gnosis.publicnode.com"],
                native_name: "Gnosis Chain",
                native_symbol: "xDai",
                native_decimals: 18,
                default_asset_type: AssetType::ERC20,
                slip44: 60,
                block_time_ms: 5_000,
                rank: 30,
                swap_supported: true,
                chain_stack: ChainStack::Native,
                min_priority_fee: 3_000_000_000,
                is_ethereum_layer2: false,
                weth_contract: Some("0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d"),
            },
            Manta {
                chain_id: "169",
                rpc_urls: ["https://pacific-rpc.manta.network/http"],
                native_name: "Manta ETH",
                native_symbol: "ETH",
                native_decimals: 18,
                default_asset_type: AssetType::ERC20,
                slip44: 60,
                block_time_ms: 2_000,
                rank: 30,
                swap_supported: true,
                chain_stack: ChainStack::Native,
                min_priority_fee: 10_000_000,
                is_ethereum_layer2: false,
                weth_contract: Some("0x0dc808adce2099a9f62aa87d9670745aba741746"),
            },
            Blast {
                chain_id: "81457",
                rpc_urls: ["https://rpc.blastblockchain.com"],
                native_name: "Blast ETH",
                native_symbol: "ETH",
                native_decimals: 18,
                default_asset_type: AssetType::ERC20,
                slip44: 60,
                block_time_ms: 2_000,
                rank: 30,
                swap_supported: true,
                chain_stack: ChainStack::Native,
                min_priority_fee: 200_000_000,
                is_ethereum_layer2: true,
                weth_contract: Some("0x4300000000000000000000000000000000000004"),
            },
            ZkSync {
                chain_id: "324",
                rpc_urls: ["https://mainnet.era.zksync.io"],
                native_name: "zkSync ETH",
                native_symbol: "ETH",
                native_decimals: 18,
                default_asset_type: AssetType::ERC20,
                slip44: 60,
                block_time_ms: 1_000,
                rank: 30,
                swap_supported: true,
                chain_stack: ChainStack::ZkSync,
                min_priority_fee: 20_000_000,
                is_ethereum_layer2: true,
                weth_contract: Some("0x5AEa5775959fBC2557Cc8789bC1bf90A239D9a91"),
            },
            Linea {
                chain_id: "59144",
                rpc_urls: ["https://linea.drpc.org"],
                native_name: "Linea ETH",
                native_symbol: "ETH",
                native_decimals: 18,
                default_asset_type: AssetType::ERC20,
                slip44: 60,
                block_time_ms: 1_000,
                rank: 30,
                swap_supported: true,
                chain_stack: ChainStack::Native,
                min_priority_fee: 50_000_000,
                is_ethereum_layer2: true,
                weth_contract: Some("0xe5D7C2a44FfDDf6b295A15c148167daaAf5Cf34f"),
            },
            Mantle {
                chain_id: "5000",
                rpc_urls: ["https://rpc.mantle.xyz"],
                native_name: "Mantle",
                native_symbol: "MNT",
                native_decimals: 18,
                default_asset_type: AssetType::ERC20,
                slip44: 60,
                block_time_ms: 1_000,
                rank: 30,
                swap_supported: true,
                chain_stack: ChainStack::Native,
                min_priority_fee: 10_000_000,
                is_ethereum_layer2: true,
                weth_contract: Some("0x78c1b0C915c4FAA5FffA6CAbf0219DA63d7f4cb8"),
            },
            Celo {
                chain_id: "42220",
                rpc_urls: ["https://forno.celo.org"],
                native_name: "Celo",
                native_symbol: "CELO",
                native_decimals: 18,
                default_asset_type: AssetType::ERC20,
                slip44: 60,
                block_time_ms: 1_000,
                rank: 30,
                swap_supported: true,
                chain_stack: ChainStack::Optimism,
                min_priority_fee: 10_000_000,
                is_ethereum_layer2: true,
                weth_contract: Some("0x471EcE3750Da237f93B8E339c536989b8978a438"),
            },
            World {
                chain_id: "480",
                rpc_urls: ["https://worldchain-mainnet.gateway.tenderly.co"],
                native_name: "World ETH",
                native_symbol: "ETH",
                native_decimals: 18,
                default_asset_type: AssetType::ERC20,
                slip44: 60,
                block_time_ms: 2_000,
                rank: 30,
                swap_supported: true,
                chain_stack: ChainStack::Optimism,
                min_priority_fee: 1_000_000,
                is_ethereum_layer2: true,
                weth_contract: Some("0x4200000000000000000000000000000000000006"),
            },
            Sonic {
                chain_id: "146",
                rpc_urls: ["https://rpc.soniclabs.com"],
                native_name: "Sonic",
                native_symbol: "S",
                native_decimals: 18,
                default_asset_type: AssetType::ERC20,
                slip44: 60,
                block_time_ms: 500,
                rank: 30,
                swap_supported: true,
                chain_stack: ChainStack::Native,
                min_priority_fee: 10_000_000,
                is_ethereum_layer2: false,
                weth_contract: Some("0x039e2fB66102314Ce7b64Ce5Ce3E5183bc94aD38"),
            },
            Abstract {
                chain_id: "2741",
                rpc_urls: ["https://api.mainnet.abs.xyz"],
                native_name: "Abstract",
                native_symbol: "ETH",
                native_decimals: 18,
                default_asset_type: AssetType::ERC20,
                slip44: 60,
                block_time_ms: 1_000,
                rank: 35,
                swap_supported: true,
                chain_stack: ChainStack::ZkSync,
                min_priority_fee: 1_000_000,
                is_ethereum_layer2: true,
                weth_contract: Some("0x3439153EB7AF838Ad19d56E1571FBD09333C2809"),
            },
            Berachain {
                chain_id: "80094",
                rpc_urls: ["https://rpc.berachain.com"],
                native_name: "Berachain",
                native_symbol: "BERA",
                native_decimals: 18,
                default_asset_type: AssetType::ERC20,
                slip44: 60,
                block_time_ms: 2_000,
                rank: 35,
                swap_supported: true,
                chain_stack: ChainStack::Native,
                min_priority_fee: 1_000_000_000,
                is_ethereum_layer2: false,
                weth_contract: Some("0x6969696969696969696969696969696969696969"),
            },
            Ink {
                chain_id: "57073",
                rpc_urls: ["https://rpc-qnd.inkonchain.com"],
                native_name: "Ink ETH",
                native_symbol: "ETH",
                native_decimals: 18,
                default_asset_type: AssetType::ERC20,
                slip44: 60,
                block_time_ms: 1_000,
                rank: 35,
                swap_supported: true,
                chain_stack: ChainStack::Optimism,
                min_priority_fee: 1_000_000,
                is_ethereum_layer2: true,
                weth_contract: Some("0x4200000000000000000000000000000000000006"),
            },
            Unichain {
                chain_id: "130",
                rpc_urls: ["https://mainnet.unichain.org"],
                native_name: "Unichain ETH",
                native_symbol: "ETH",
                native_decimals: 18,
                default_asset_type: AssetType::ERC20,
                slip44: 60,
                block_time_ms: 1_000,
                rank: 35,
                swap_supported: true,
                chain_stack: ChainStack::Optimism,
                min_priority_fee: 1_000_000,
                is_ethereum_layer2: true,
                weth_contract: Some("0x4200000000000000000000000000000000000006"),
            },
            Hyperliquid {
                chain_id: "999",
                rpc_urls: ["https://rpc.hyperliquid.xyz/evm"],
                native_name: "HyperEVM",
                native_symbol: "HYPE",
                native_decimals: 18,
                default_asset_type: AssetType::ERC20,
                slip44: 60,
                block_time_ms: 2_000,
                rank: 40,
                swap_supported: true,
                chain_stack: ChainStack::Native,
                min_priority_fee: 1_000_000_000,
                is_ethereum_layer2: false,
                weth_contract: Some("0x5555555555555555555555555555555555555555"),
            },
            Monad {
                chain_id: "143",
                rpc_urls: ["https://rpc.monad.xyz"],
                native_name: "Monad",
                native_symbol: "MON",
                native_decimals: 18,
                default_asset_type: AssetType::ERC20,
                slip44: 60,
                block_time_ms: 500,
                rank: 40,
                swap_supported: true,
                chain_stack: ChainStack::Native,
                min_priority_fee: 1_000_000_000,
                is_ethereum_layer2: false,
                weth_contract: Some("0x3bd359C1119dA7Da1D913D1C4D2B7c461115433A"),
            },
            XLayer {
                chain_id: "196",
                rpc_urls: ["https://rpc.xlayer.tech"],
                native_name: "X Layer",
                native_symbol: "OKB",
                native_decimals: 18,
                default_asset_type: AssetType::ERC20,
                slip44: 60,
                block_time_ms: 2_000,
                rank: 30,
                swap_supported: false,
                chain_stack: ChainStack::Native,
                min_priority_fee: 1_000_000_000,
                is_ethereum_layer2: true,
                weth_contract: Some("0xe538905cf8410324e03a5a23c1c177a474d59b2b"),
            },
            Stable {
                chain_id: "988",
                rpc_urls: ["https://rpc.stable.xyz"],
                native_name: "Stable",
                native_symbol: "gUSDT",
                native_decimals: 18,
                default_asset_type: AssetType::ERC20,
                slip44: 60,
                block_time_ms: 1_000,
                rank: 30,
                swap_supported: false,
                chain_stack: ChainStack::Native,
                min_priority_fee: 1_000_000,
                is_ethereum_layer2: false,
                weth_contract: Some("0x779Ded0c9e1022225f8E0630b35a9b54bE713736"),
            },
        }
    };
}
