/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct AddressName: Codable, Equatable, Hashable, Sendable {
	public let chain: Chain
	public let address: String
	public let name: String
	public let type: AddressType?
	public let status: VerificationStatus

	public init(chain: Chain, address: String, name: String, type: AddressType?, status: VerificationStatus) {
		self.chain = chain
		self.address = address
		self.name = name
		self.type = type
		self.status = status
	}
}
