/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct AuthNonce: Codable, Sendable {
	public let nonce: String
	public let timestamp: UInt32

	public init(nonce: String, timestamp: UInt32) {
		self.nonce = nonce
		self.timestamp = timestamp
	}
}

public struct AuthPayload: Codable, Sendable {
	public let deviceId: String
	public let chain: Chain
	public let address: String
	public let nonce: String
	public let signature: String

	public init(deviceId: String, chain: Chain, address: String, nonce: String, signature: String) {
		self.deviceId = deviceId
		self.chain = chain
		self.address = address
		self.nonce = nonce
		self.signature = signature
	}
}

public struct AuthenticatedRequest<T: Codable & Sendable>: Codable, Sendable {
	public let auth: AuthPayload
	public let data: T

	public init(auth: AuthPayload, data: T) {
		self.auth = auth
		self.data = data
	}
}
