/*
 Generated by typeshare 1.13.3
 */

import Foundation

public enum BalanceType: String, Codable, CaseIterable, Equatable, Sendable {
	case available
	case locked
	case frozen
	case staked
	case pending
	case pendingUnconfirmed
	case rewards
	case reserved
	case earn
}
