/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct FiatProvider: Codable, Equatable, Hashable, Sendable {
	public let id: String
	public let name: String
	public let imageUrl: String?

	public init(id: String, name: String, imageUrl: String?) {
		self.id = id
		self.name = name
		self.imageUrl = imageUrl
	}
}

public enum FiatProviderName: String, Codable, Equatable, Hashable, Sendable {
	case mercuryo
	case transak
	case moonPay = "moonpay"
	case ramp
	case banxa
	case paybis
	case flashnet
}
