/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct FiatQuote: Codable, Equatable, Hashable, Sendable {
	public let id: String
	public let provider: FiatProvider
	public let type: FiatQuoteType
	public let fiatAmount: Double
	public let fiatCurrency: String
	public let cryptoAmount: Double
	public let paymentMethods: [PaymentType]

	public init(id: String, provider: FiatProvider, type: FiatQuoteType, fiatAmount: Double, fiatCurrency: String, cryptoAmount: Double, paymentMethods: [PaymentType]) {
		self.id = id
		self.provider = provider
		self.type = type
		self.fiatAmount = fiatAmount
		self.fiatCurrency = fiatCurrency
		self.cryptoAmount = cryptoAmount
		self.paymentMethods = paymentMethods
	}
}

public struct FiatQuoteUrl: Codable, Sendable {
	public let redirectUrl: String

	public init(redirectUrl: String) {
		self.redirectUrl = redirectUrl
	}
}

public struct FiatQuotes: Codable, Sendable {
	public let quotes: [FiatQuote]

	public init(quotes: [FiatQuote]) {
		self.quotes = quotes
	}
}
