/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct FiatProvider: Codable, Equatable, Hashable, Sendable {
	public let id: String
	public let name: String
	public let imageUrl: String?
	public let paymentMethods: [PaymentType]

	public init(id: String, name: String, imageUrl: String?, paymentMethods: [PaymentType]) {
		self.id = id
		self.name = name
		self.imageUrl = imageUrl
		self.paymentMethods = paymentMethods
	}
}

public enum FiatProviderName: String, Codable, Equatable, Hashable, Sendable {
	case mercuryo
	case transak
	case moonPay = "moonpay"
	case banxa
	case paybis
	case flashnet
}
