/*
 Generated by typeshare 1.13.3
 */

import Foundation

public enum PaymentType: String, Codable, Equatable, Hashable, Sendable {
	case card
	case googlePay = "google_pay"
	case applePay = "apple_pay"
	case cashApp = "cash_app"
	case venmo
	case sepa
	case ach
	case wire
}
