/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct PushNotificationAsset: Codable, Equatable, Sendable {
	public let assetId: String

	public init(assetId: String) {
		self.assetId = assetId
	}
}

public enum PushNotificationTypes: String, Codable, Equatable, Sendable {
	case test
	case transaction
	case asset
	case priceAlert
	case buyAsset
	case swapAsset
	case support
	case rewards
	case stake
}

public struct PushNotificationPayloadType: Codable, Equatable, Sendable {
	public let type: PushNotificationTypes

	public init(type: PushNotificationTypes) {
		self.type = type
	}
}

public struct PushNotificationReward: Codable, Equatable, Sendable {
	public let walletId: String

	public init(walletId: String) {
		self.walletId = walletId
	}
}

public struct PushNotificationStake: Codable, Equatable, Sendable {
	public let walletId: WalletId
	public let assetId: AssetId

	public init(walletId: WalletId, assetId: AssetId) {
		self.walletId = walletId
		self.assetId = assetId
	}
}

public struct PushNotificationSupport: Codable, Equatable, Sendable {
	public init() {}
}

public struct PushNotificationSwapAsset: Codable, Equatable, Sendable {
	public let fromAssetId: String
	public let toAssetId: String

	public init(fromAssetId: String, toAssetId: String) {
		self.fromAssetId = fromAssetId
		self.toAssetId = toAssetId
	}
}

public struct PushNotificationTransaction: Codable, Equatable, Sendable {
	public let walletId: String
	public let assetId: String
	public let transaction: Transaction

	public init(walletId: String, assetId: String, transaction: Transaction) {
		self.walletId = walletId
		self.assetId = assetId
		self.transaction = transaction
	}
}
