/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct ScanAddressTarget: Codable, Equatable, Sendable {
	public let assetId: AssetId
	public let address: String

	public init(assetId: AssetId, address: String) {
		self.assetId = assetId
		self.address = address
	}
}

public struct ScanTransaction: Codable, Equatable, Sendable {
	public let isMalicious: Bool
	public let isMemoRequired: Bool

	public init(isMalicious: Bool, isMemoRequired: Bool) {
		self.isMalicious = isMalicious
		self.isMemoRequired = isMemoRequired
	}
}

public struct ScanTransactionPayload: Codable, Equatable, Sendable {
	public let origin: ScanAddressTarget
	public let target: ScanAddressTarget
	public let website: String?
	public let type: TransactionType

	public init(origin: ScanAddressTarget, target: ScanAddressTarget, website: String?, type: TransactionType) {
		self.origin = origin
		self.target = target
		self.website = website
		self.type = type
	}
}

public enum AddressType: String, Codable, Equatable, Sendable {
	case address
	case contract
	case validator
	case contact
}
