/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct SimulationBalanceChange: Codable, Equatable, Hashable, Sendable {
	public let assetId: AssetId
	public let value: String

	public init(assetId: AssetId, value: String) {
		self.assetId = assetId
		self.value = value
	}
}

public struct SimulationHeader: Codable, Equatable, Hashable, Sendable {
	public let assetId: AssetId
	public let value: String

	public init(assetId: AssetId, value: String) {
		self.assetId = assetId
		self.value = value
	}
}

public enum SimulationPayloadFieldKind: String, Codable, Equatable, Hashable, Sendable {
	case contract
	case method
	case token
	case spender
	case value
	case custom
}

public enum SimulationPayloadFieldType: String, Codable, Equatable, Hashable, Sendable {
	case text
	case address
	case timestamp
}

public enum SimulationPayloadFieldDisplay: String, Codable, Equatable, Hashable, Sendable {
	case primary
	case secondary
}

public struct SimulationPayloadField: Codable, Equatable, Hashable, Sendable {
	public let kind: SimulationPayloadFieldKind
	public let label: String?
	public let value: String
	public let fieldType: SimulationPayloadFieldType
	public let display: SimulationPayloadFieldDisplay

	public init(kind: SimulationPayloadFieldKind, label: String?, value: String, fieldType: SimulationPayloadFieldType, display: SimulationPayloadFieldDisplay) {
		self.kind = kind
		self.label = label
		self.value = value
		self.fieldType = fieldType
		self.display = display
	}
}

public enum SimulationSeverity: String, Codable, Equatable, Hashable, Sendable {
	case low
	case warning
	case critical
}

public struct SimulationWarning: Codable, Equatable, Hashable, Sendable {
	public let severity: SimulationSeverity
	public let warning: SimulationWarningType
	public let message: String?

	public init(severity: SimulationSeverity, warning: SimulationWarningType, message: String?) {
		self.severity = severity
		self.warning = warning
		self.message = message
	}
}

public struct SimulationResult: Codable, Equatable, Hashable, Sendable {
	public let warnings: [SimulationWarning]
	public let balanceChanges: [SimulationBalanceChange]
	public let payload: [SimulationPayloadField]
	public let header: SimulationHeader?

	public init(warnings: [SimulationWarning], balanceChanges: [SimulationBalanceChange], payload: [SimulationPayloadField], header: SimulationHeader?) {
		self.warnings = warnings
		self.balanceChanges = balanceChanges
		self.payload = payload
		self.header = header
	}
}
