/*
 Generated by typeshare 1.13.3
 */

import Foundation

public enum SwapProvider: String, Codable, Equatable, Hashable, Sendable {
	case uniswapV3 = "uniswap_v3"
	case uniswapV4 = "uniswap_v4"
	case pancakeswapV3 = "pancakeswap_v3"
	case aerodrome
	case panora
	case thorchain
	case jupiter
	case okx
	case across
	case oku
	case wagmi
	case stonfiV2 = "stonfi_v2"
	case mayan
	case chainflip
	case nearIntents = "near_intents"
	case cetusAggregator = "cetus_aggregator"
	case relay
	case hyperliquid
	case orca
}
