/*
 Generated by typeshare 1.13.3
 */

import Foundation

public enum TransactionType: String, Codable, CaseIterable, Equatable, Sendable {
	case transfer
	case transferNFT
	case swap
	case tokenApproval
	case stakeDelegate
	case stakeUndelegate
	case stakeRewards
	case stakeRedelegate
	case stakeWithdraw
	case stakeFreeze
	case stakeUnfreeze
	case assetActivation
	case smartContractCall
	case perpetualOpenPosition
	case perpetualClosePosition
	case perpetualModifyPosition
	case earnDeposit
	case earnWithdraw
}
