/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct TransactionNFTTransferMetadata: Codable, Sendable {
	public let assetId: String
	public let name: String?

	public init(assetId: String, name: String?) {
		self.assetId = assetId
		self.name = name
	}
}

public struct TransactionPerpetualMetadata: Codable, Sendable {
	public let pnl: Double
	public let price: Double
	public let direction: PerpetualDirection
	public let provider: PerpetualProvider?

	public init(pnl: Double, price: Double, direction: PerpetualDirection, provider: PerpetualProvider?) {
		self.pnl = pnl
		self.price = price
		self.direction = direction
		self.provider = provider
	}
}

public struct TransactionResourceTypeMetadata: Codable, Sendable {
	public let resourceType: Resource

	public init(resourceType: Resource) {
		self.resourceType = resourceType
	}
}

public struct TransactionSmartContractMetadata: Codable, Sendable {
	public let methodName: String

	public init(methodName: String) {
		self.methodName = methodName
	}
}

public struct TransactionSwapMetadata: Codable, Equatable, Hashable, Sendable {
	public let fromAsset: AssetId
	public let fromValue: String
	public let toAsset: AssetId
	public let toValue: String
	public let provider: String?

	public init(fromAsset: AssetId, fromValue: String, toAsset: AssetId, toValue: String, provider: String?) {
		self.fromAsset = fromAsset
		self.fromValue = fromValue
		self.toAsset = toAsset
		self.toValue = toValue
		self.provider = provider
	}
}
