[package]
name = "number_formatter"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
num-bigint = { workspace = true }
num-traits = { workspace = true }
bigdecimal = { workspace = true }
rusty-money = { workspace = true }
