[package]
name = "swapper"
edition = { workspace = true }
version = { workspace = true }

[dependencies]
serde = { workspace = true }
reqwest = { workspace = true }

primitives = { path = "../primitives" }
gem_solana = { path = "../gem_solana" }
gem_evm = { path = "../gem_evm" }
