[package]
name = "chain_primitives"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
primitives = { path = "../primitives" }
alloy-primitives = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }
