[package]
name = "swapper-dump"
version = "0.1.0"
edition = "2021"

[dependencies]
gemstone = { path = "../../gemstone", features = ["reqwest_provider"] }
primitives = { path = "../../crates/primitives" }
tokio = { workspace = true }

[[bin]]
name = "swapper-dump"
path = "src/main.rs"
