[package]
name = "gem_swapper"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[features]
default = []
reqwest_provider = ["dep:reqwest"]
swap_integration_tests = ["reqwest_provider"]

[dependencies]
primitives = { path = "../primitives" }
gem_solana = { path = "../gem_solana", features = ["rpc"] }
gem_ton = { path = "../gem_ton", features = ["rpc"] }
gem_tron = { path = "../gem_tron", features = ["rpc"] }
gem_evm = { path = "../gem_evm", features = ["rpc"] }
gem_sui = { path = "../gem_sui", features = ["rpc"] }
gem_aptos = { path = "../gem_aptos", features = ["rpc"] }
gem_hash = { path = "../gem_hash" }
gem_jsonrpc = { path = "../gem_jsonrpc" }
anyhow = "1.0"
gem_client = { path = "../gem_client" }
gem_hypercore = { path = "../gem_hypercore" }
gem_bitcoin = { path = "../gem_bitcoin", features = ["rpc"] }
gem_cardano = { path = "../gem_cardano", features = ["rpc"] }
gem_algorand = { path = "../gem_algorand", features = ["rpc"] }
gem_stellar = { path = "../gem_stellar", features = ["rpc"] }
gem_xrp = { path = "../gem_xrp", features = ["rpc"] }
gem_near = { path = "../gem_near", features = ["rpc"] }
gem_polkadot = { path = "../gem_polkadot", features = ["rpc"] }
serde_serializers = { path = "../serde_serializers" }
chain_traits = { path = "../chain_traits" }
number_formatter = { path = "../number_formatter" }
gem_macro = { path = "../gem_macro" }

reqwest = { workspace = true, optional = true }

bcs.workspace = true
sui-types = { workspace = true }
sui-transaction-builder = { workspace = true }

strum = { workspace = true }
chrono = { workspace = true }

base64.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_urlencoded.workspace = true
async-trait.workspace = true
alloy-primitives.workspace = true
alloy-sol-types.workspace = true
hex.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
futures.workspace = true
bs58 = { workspace = true }
solana-primitives = "0.2.1"
bigdecimal.workspace = true
rand.workspace = true

[dev-dependencies]
tokio.workspace = true

[[test]]
name = "integration_test"
test = false
