[package]
name = "swap_primitives"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
typeshare = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }

primitives = { path = "../primitives" }
