[package]
name = "pricer_dex"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
async-trait =  { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }

primitives = { path = "../primitives" }

[dev-dependencies]
tokio.workspace = true

[[test]]
name = "integration_test"
test = false
