[package]
name = "pricer_dex"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

gem_client = { path = "../gem_client" }
primitives = { path = "../primitives" }
serde_serializers = { path = "../serde_serializers" }

[dev-dependencies]
tokio.workspace = true

[[test]]
name = "integration_test"
test = false
