[package]
name = "name_resolver"
edition = { workspace = true }
version = { workspace = true }

[dependencies]
anyhow.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
reqwest.workspace = true
async-trait = { workspace = true }
base64 = { workspace = true }
hex = { workspace = true }
lazy_static = { workspace = true }
alloy-primitives.workspace = true
alloy-sol-types.workspace = true
alloy-ens.workspace = true
gem_jsonrpc = { path = "../gem_jsonrpc", features = ["client"] }
idna = { workspace = true }

settings = { path = "../settings" }
primitives = { path = "../primitives" }
gem_hash = { path = "../gem_hash" }
gem_evm = { path = "../gem_evm" }
gem_ton = { path = "../gem_ton" }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokio-test = { version = "*" }

[[test]]
name = "integration_test"
test = false
