[package]
name = "name_resolver"
edition = { workspace = true }
version = { workspace = true }

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
hex = { workspace = true }
lazy_static = { workspace = true }
alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
anyhow = { workspace = true }
url = { workspace = true, features = ["serde"] }
alloy-ens = "1.0.7"
alloy-json-rpc = "1.0.7"
alloy-rpc-client = "1.0.7"
alloy-rpc-types = "1.0.7"
alloy-transport-http = "1.0.7"
alloy-contract = "1.0.7"

settings = { path = "../settings" }
primitives = { path = "../primitives" }
gem_hash = { path = "../gem_hash" }
gem_evm = { path = "../gem_evm" }
gem_ton = { path = "../gem_ton" }

[dev-dependencies]
tokio-test = { version = "*" }

[[test]]
name = "integration_test"
test = false
