[package]
name = "nft_client"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
reqwest = { workspace = true }

primitives = { path = "../primitives" }
storage = { path = "../storage" }
nft_provider = { path = "../nft_provider" }