[package]
name = "security_provider"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
primitives = { path = "../primitives" }
reqwest = { workspace = true }
uuid = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
gem_client = { path = "../gem_client", features = ["reqwest"] }

[dev-dependencies]
serde_json = { workspace = true }
tokio = { workspace = true }
settings = { path = "../settings" }

[[test]]
name = "integration_test"
test = false
