[package]
name = "security_goplus"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
security_provider = { path = "../security_provider" }
reqwest = { workspace = true }
