[package]
name = "security_goplus"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
serde = { workspace = true }
security_provider = { path = "../security_provider" }
reqwest-enum = { workspace = true }
