name: CI on macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_ios:
    runs-on: macos-latest-xlarge
    defaults:
      run:
        working-directory: ./
        
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build Gemstone
      run: |
        make prepare-apple && make apple BUILD_MODE=release
      working-directory: gemstone
