name: CI - Gemstone iOS

on:
  push:
    branches: ["main"]
    paths:
      - "gemstone/**"
  pull_request:
    branches: ["main"]
    paths:
      - "gemstone/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  build_ios:
    runs-on: macos-26
    defaults:
      run:
        working-directory: gemstone
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-rust-ci

      - name: Install iOS targets
        run: just install-ios-targets

      - name: Build iOS
        run: just build-ios

      - name: Test iOS
        run: just test-ios
