name: CI - Lint
on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v6
      - name: Setup Rust
        uses: ./.github/actions/setup-rust-ci
        with:
          sccache: "false"

      - name: Run Lint
        run: just lint
